require('base')
require('maps')
require('plugins')
require('p-mason')
require('p-null')
require('p-lspsaga')
require('p-tree')
require('color')
-- require('p-lualine')
require('p-telescope')
require('p-bookmark')
require('p-lspkind')
require('p-cmp')
require('p-snip')
-- require('p-treesitter')
require('p-hop')
require('style')
require('other')
