require('base')
require('maps')
require('plugins')
require('p-coc')
require('p-tree')
require('color')
-- require('p-lualine')
require('p-telescope')
require('p-bookmark')
require('p-hop')
require('style')
require('other')
-- LSP 相关的
-- require('p-mason')
-- require('p-null')
-- require('p-lspsaga')
-- require('p-lspkind')
-- require('p-treesitter')
-- require('p-cmp')
-- require('p-snip')
